### ISSUE TITLE
Finish the GitHub Basics course 

### ISSUE THREAD

**Issue by mari-doge-shibe** [mari-doge-shibe/Treehouse#2]
## TODO
*Course left to complete the GitHub Basics course*
* [x] Working By Yourself
* [x] Working on a Team
* [x] Create a Web Presence on GitHub
* [x] Get Involved in Open Source

:tada: :ok_woman: :confetti_ball:

**Comment by mari-doge-shibe** [comment]
Course completed
